import {FieldTypes, TField} from '@/forms/types'

export const fields: TField[] = [
	{
		type: FieldTypes.TEXT,
		name: 'model',
		placeholder: '',
		label: 'Car Brand',
		required: true,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.TEXT,
		name: 'year',
		placeholder: '',
		label: 'Year',
		required: true,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.TEXT,
		name: 'mileage',
		placeholder: '',
		label: 'Mileage',
		required: false,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.TEXT,
		name: 'color',
		placeholder: '',
		label: 'Color',
		required: false,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.TEXT,
		name: 'status',
		placeholder: '',
		label: 'Status',
		required: true,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.TEXT,
		name: 'startBid',
		placeholder: '',
		label: 'Opening Bid',
		required: true,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
	{
		type: FieldTypes.DATE,
		name: 'expired',
		placeholder: '',
		label: 'Expired date',
		required: true,
		labelWidth: 20,
		layout: 'vertical',
		inputWidth: 'auto',
	},
]
